using System;

namespace Fiddler;

/// <summary>
/// This enumeration provides the values for the Session object's BitFlags field
/// </summary>
[Flags]
public enum SessionFlags
{
	/// <summary>
	/// No flags are set
	/// </summary>
	None = 0,
	/// <summary>
	/// The request originally arrived with a URL specifying the HTTPS protocol.
	/// </summary>
	IsHTTPS = 1,
	/// <summary>
	/// The request originally arrived with a URL specifying the FTP protocol.
	/// </summary>
	IsFTP = 2,
	/// <summary>
	/// Ignore this traffic; do not buffer, store, or call event handlers
	/// </summary>
	Ignored = 4,
	/// <summary>
	/// The client pipe was reused
	/// </summary>
	ClientPipeReused = 8,
	/// <summary>
	/// The server pipe was reused
	/// </summary>
	ServerPipeReused = 0x10,
	/// <summary>
	/// The request was transmitted to the server when its headers were complete
	/// </summary>
	RequestStreamed = 0x20,
	/// <summary>
	/// The response was streamed
	/// </summary>
	ResponseStreamed = 0x40,
	/// <summary>
	/// The request was generated by Fiddler itself (e.g. the Composer tab)
	/// </summary>
	RequestGeneratedByFiddler = 0x80,
	/// <summary>
	/// The response was generated by Fiddler itself (e.g. AutoResponder or utilCreateResponseAndBypassServer)
	/// </summary>
	ResponseGeneratedByFiddler = 0x100,
	/// <summary>
	/// This session was loaded from a .SAZ File
	/// </summary>
	LoadedFromSAZ = 0x200,
	/// <summary>
	///  This session was loaded from some other tool
	/// </summary>
	ImportedFromOtherTool = 0x400,
	/// <summary>
	/// This request was sent to an upstream (CERN) gateway proxy
	/// </summary>
	SentToGateway = 0x800,
	/// <summary>
	/// This is a "blind" CONNECT tunnel for HTTPS traffic 
	/// </summary>
	IsBlindTunnel = 0x1000,
	/// <summary>
	/// This is a CONNECT tunnel which decrypts HTTPS traffic as it flows through
	/// </summary>
	IsDecryptingTunnel = 0x2000,
	/// <summary>
	/// This response was served from a client cache, bypassing Fiddler. Fiddler only "sees" this session because other software reported it to Fiddler
	/// </summary>
	ServedFromCache = 0x4000,
	/// <summary>
	/// There was a HTTP Protocol violation in the client's request
	/// </summary>
	ProtocolViolationInRequest = 0x8000,
	/// <summary>
	/// There was a HTTP Protocol violation in the server's response
	/// </summary>
	ProtocolViolationInResponse = 0x10000,
	/// <summary>
	/// Response body was dropped, e.g due to fiddler.network.streaming.ForgetStreamedData or log-drop-response-body flag
	/// </summary>
	ResponseBodyDropped = 0x20000,
	/// <summary>
	/// This is a CONNECT tunnel for WebSocket traffic
	/// </summary>
	IsWebSocketTunnel = 0x40000,
	/// <summary>
	/// This request was sent using the SOCKS protocol
	/// </summary>
	SentToSOCKSGateway = 0x80000,
	/// <summary>
	/// Request body was dropped, e.g due to log-drop-request-body flag
	/// </summary>
	RequestBodyDropped = 0x100000,
	/// <summary>
	/// The request was to create a RPC tunnel (e.g. on an RPC_OUT_DATA request)
	/// </summary>
	IsRPCTunnel = 0x200000
}
